# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Charlotte-Ngs
tagline:          The Project Platform
url:              http://charlotte-ngs.github.io
#paginate:         1
baseurl:          '/'
author:
  name:           Charlotte-Ngs Team
  url:            
  email:          ngs.charlotte@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/charlotte-ngs.github.io

# page list 
pages_list:       
  About: '/about'
  Archive: '/archive'
  Teaching: '/teaching'
