# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Charlotte-Ngs
tagline:          The Project Platform
url:              http://charlotte-ngs.github.io
paginate:         1
baseurl:          /
author:
  name:           Charlotte-Ngs Team
  url:            
  email:          ngs.charlotte@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/charlotte-ngs.github.io
